apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-proxy-pv-work
  labels:
    app: apache-proxy
    type: local
    storage-tier: apache-proxy-pv-work
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/apache2/bitnami/app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-proxy-pv-vhosts
  labels:
    type: local
    storage-tier: apache-proxy-pv-vhosts
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/apache2/bitnami/vhosts
